### ISSUE TITLE
inline css

### ISSUE THREAD

**Issue by jerrygreen** [JerryGreen/chiliz#5]
To use that https://github.com/jsxstyle/jsxstyle?

Or better add [nextjs](https://nextjs.org)?

---

- [ ] Before merge, to check out google page speed rank, trace how it will affect:

https://developers.google.com/speed/pagespeed/insights/?url=chiliz.ru

This task is about that recommended optimization

Overall page stat:
===
![image](https://user-images.githubusercontent.com/13215662/55159729-8c6c8a80-5183-11e9-8fae-f6756d47d170.png)

Recommended optimization:
===
![image](https://user-images.githubusercontent.com/13215662/55159774-9e4e2d80-5183-11e9-9db3-d57d06153f71.png)

**Comment by jerrygreen** [comment]
P.S. funny thing
===
![image](https://user-images.githubusercontent.com/13215662/55160393-0d785180-5185-11e9-8f56-48027b118019.png)
(https://developers.google.com/speed/pagespeed/insights/?url=chiliz.000webhostapp.com)

**Comment by JerryGreen** [comment]
- [ ] Add nextjs ?

**Comment by jerrygreen** [comment]
Fixed by #32:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/13215662/72248115-31275e00-3618-11ea-9f31-508209fce15e.png">
